services:
  frontend:
    image: artcreation-dv_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    image: artcreation-dv_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
