services:
  frontend:
    image: artcreation-dv_frontend
    container_name: artcreation-dv_fe-container
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        API_URL: ${API_URL}
    ports:
      - "4201:80"
    expose:
      - 80
    depends_on:
      - backend

  backend:
    image: artcreation-dv_backend
    container_name: artcreation-dv_be-container
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
